MSPM0Gxx0xEdgeAIAPIDocument: filterbank_feature_extract.c File Reference
filterbank_feature_extract.c File Reference
Detailed Description
Implementation of filterbank-based feature extraction for processing.
This file contains the implementation of feature extraction using filterbank techniques with NPU hardware acceleration. It processes samples through a series of filterbank operations to extract meaningful features for machine learning applications. The implementation follows a multi-stage processing pipeline:
Sample packing into frames with configurable overlap
NPU-accelerated filterbank processing
Two-pass processing (MSB and LSB) for extended numerical precision
Max-pooling for feature dimensionality reduction
Feature normalization, scaling, and formatting
Window management for temporal context preservation
This implementation is optimized for low-power operation on TI MSP devices with integrated Neural Processing Unit (NPU) hardware acceleration.
#include "filterbank_feature_extract.h"
#include "constants.h"
#include "model_AUTOGEN.h"
#include <string.h>
#include <limits.h>
#include "fe_model/fe_model.h"
#include <ti/devices/msp/msp.h>
#include "ti_msp_dl_config.h"
#include <ti/devices/msp/peripherals/hw_npu.h>
Macros
#define FBFE_CTL1_ADDR_SHIFT_BITS (18u)
Shift bits for NPU CTL1 address field.
#define FBFE_CTL1_ADDR_MASK (0xcfffu)
Mask for NPU CTL1 address field.
#define FBFE_CTL1_OFMAP_SHIFT_BITS (16u)
Shift bits for NPU CTL1 OFMAP field.
#define FBFE_MMR_STRIDE_STEP (2u)
Step size for MMR stride operations.
#define FBFE_MSB_COMBINE_SHIFT_BITS (8u)
Shift bits for MSB combination in the 2-bit weights flow.
#define FBFE_ARBIAS0_ROW_WORD64 (128u)
Row word count for ARBIAS0.
#define FBFE_WORD_ADDR_SHIFT_BITS (2u)
Shift bits for word addressing.
#define FBFE_WORD_ADDR_16BIT_MASK (0xffffu)
Mask for 16-bit word addressing.
#define FE_SIGNCHK_MASK (0xFFFDFFFFu)
Mask for sign check in ACCREG sign-extension behavior.
#define FE_SIGNCHK_VAL (0xFFFFFFFFu)
Value for sign check in ACCREG sign-extension behavior.
#define FE_SIGNEXT_OR (0xFFFC0000u)
OR mask for sign extension in ACCREG sign-extension behavior.
#define FE_CTL0_MSB (0x12019u)
CTL0 value for MSB pass in 2-bit weights flow.
#define FE_CTL0_LSB (0x12011u)
CTL0 value for LSB pass in 2-bit weights flow.
Functions
void TINIE_start (void)
Start the NPU layer execution.
static void FBFE_ShiftNNInputWindow (FBFE_Ctx *ctx, const uint8_t *new_frame)
Shift the neural network input window to incorporate a new frame.
bool FBFE_Init (FBFE_Ctx *ctx, const FBFE_Config *cfg, uint8_t *final_features, size_t final_features_bytes)
Initialize the filterbank feature extraction context.
bool FBFE_PushSample (FBFE_Ctx *ctx, uint16_t sample)
Push a new audio sample for processing.
bool FBFE_RunOneFrame (FBFE_Ctx *ctx)
Process one frame of data through the filterbank.
Variables
static int16_t g_frame_buffer [NUM_SAMPLES]
Global buffer for storing frame samples.
static int8_t g_fb_input [FB_INPUT_BYTES]
Global buffer for NPU input data.
static int32_t g_msbTemp [MODEL_MAX_OUT_CH_PER_ITER]
Temporary buffer for storing MSB pass results.
static int32_t g_lsbTemp [MODEL_MAX_OUT_CH_PER_ITER]
Temporary buffer for storing LSB pass results.
static int32_t g_maxValues [MODEL_CONV_OUT_CHANNELS]
Buffer for storing maximum values across all strides.
static uint8_t g_singleOut [MODEL_CONV_OUT_CHANNELS]
Buffer for storing single iteration outputs.
static uint8_t g_maxpool [MODEL_CONV_OUT_CHANNELS]
Buffer for storing maxpool operation results.
Function Documentation
TINIE_start()
void TINIE_start (void)
Start the NPU layer execution.
This function triggers the execution of a layer in the NPU by setting the START bit in the CTL5 register.
Returns
None
References NPU_getCtlReg().
Referenced by FBFE_RunOneFrame().
FBFE_ShiftNNInputWindow()
static void FBFE_ShiftNNInputWindow (FBFE_Ctx * ctx, const uint8_t * new_frame) static
Shift the neural network input window to incorporate a new frame.
This function updates the feature window by shifting existing features and adding the new frame. It maintains a sliding window of features for temporal context in the neural network input.
Parameters
[in,out] ctx Pointer to the filterbank context.
[in] new_frame Pointer to the new frame data to be incorporated.
Returns
None
References FBFE_Ctx::final_features.
Referenced by FBFE_RunOneFrame().
FBFE_Init()
bool FBFE_Init (FBFE_Ctx * ctx, const FBFE_Config * cfg, uint8_t * final_features, size_t final_features_bytes)
Initialize the filterbank feature extraction context.
This function initializes the filterbank feature extraction context with the provided configuration and output buffer. It performs parameter validation, sets up the context structure, binds internal buffers, and ensures a deterministic initial state.
Parameters
[in,out] ctx Pointer to the context structure to initialize.
[in] cfg Pointer to the configuration structure.
[in] final_features Pointer to the buffer where final features will be stored.
[in] final_features_bytes Size in bytes of the final features buffer.
Returns
true if initialization was successful, false otherwise.
References FBFE_Ctx::cfg, FBFE_Ctx::fb_input, FBFE_Ctx::final_features, FBFE_Ctx::final_features_bytes, FBFE_Ctx::frame_buffer, g_fb_input, g_frame_buffer, g_lsbTemp, g_maxpool, g_maxValues, g_msbTemp, g_singleOut, FBFE_Ctx::inited, FBFE_Ctx::lsb_temp, FBFE_Ctx::max_values, FBFE_Ctx::maxpool_outputs, FBFE_Ctx::msb_temp, FBFE_Ctx::pack_index, FBFE_Ctx::sample_index, and FBFE_Ctx::single_out.
FBFE_PushSample()
bool FBFE_PushSample (FBFE_Ctx * ctx, uint16_t sample)
Push a new audio sample for processing.
Push a new sample for processing.
This function adds a new sample to the processing pipeline. It handles the sample packing, byte splitting, and frame buffer management. When enough samples have been collected to form a complete frame, the function prepares the data for NPU processing by properly arranging it in the input buffer. The sample packing process follows these steps:
Split the 16-bit sample into most and least significant bytes using configured masks
Store these bytes in temporary buffers
When enough samples are collected (pack_size=4), pack them into the frame buffer
When a complete frame is collected, update the input buffer with overlap handling
The byte packing scheme optimizes memory usage and aligns data for efficient NPU processing by organizing samples in a specific pattern.
Parameters
[in,out] ctx Pointer to the initialized context structure.
[in] sample The sample value to process.
Returns
true if the sample was successfully added, false if the context is invalid.
References FBFE_Ctx::cfg, FBFE_Ctx::fb_input, FBFE_Ctx::frame_buffer, FBFE_Ctx::inited, FBFE_Ctx::ls_bytes, FBFE_Config::ls_mask, FBFE_Ctx::ms_bytes, FBFE_Config::ms_mask, FBFE_Config::ms_shift, FBFE_Ctx::pack_index, and FBFE_Ctx::sample_index.
FBFE_RunOneFrame()
bool FBFE_RunOneFrame (FBFE_Ctx * ctx)
Process one frame of data through the filterbank.
This function executes the filterbank feature extraction process on a complete frame of data using the NPU hardware accelerator. It performs the following steps:
Initializes NPU registers
Processes data in blocks, corresponding to channel groups
For each block, performs multiple stride iterations
For each stride, executes both MSB and LSB passes
Combines MSB and LSB results and tracks maximum values
Applies scaling, offset, and quantization to the output features
Updates the sliding feature window with the new results
Parameters
[in,out] ctx Pointer to the initialized context structure.
Returns
true if the frame was successfully processed, false if the context is invalid.
References FBFE_Ctx::fb_input, FBFE_ARBIAS0_ROW_WORD64, FBFE_CTL1_ADDR_MASK, FBFE_CTL1_ADDR_SHIFT_BITS, FBFE_CTL1_OFMAP_SHIFT_BITS, FBFE_MMR_STRIDE_STEP, FBFE_MSB_COMBINE_SHIFT_BITS, FBFE_ShiftNNInputWindow(), FBFE_WORD_ADDR_16BIT_MASK, FBFE_WORD_ADDR_SHIFT_BITS, FE_CTL0_LSB, FE_CTL0_MSB, FE_SIGNCHK_MASK, FE_SIGNCHK_VAL, FE_SIGNEXT_OR, FBFE_Ctx::inited, FBFE_Ctx::lsb_temp, FBFE_Ctx::max_values, FBFE_Ctx::maxpool_outputs, FBFE_Ctx::msb_temp, FBFE_Ctx::single_out, and TINIE_start().
Variable Documentation
g_frame_buffer
int16_t g_frame_buffer[NUM_SAMPLES] static
Global buffer for storing frame samples.
This buffer holds the raw samples for a complete processing frame.
Referenced by FBFE_Init().
g_fb_input
int8_t g_fb_input[FB_INPUT_BYTES] static
Global buffer for NPU input data.
This buffer holds the packed byte representation of the data, with proper overlapping between frames for continuous processing.
Referenced by FBFE_Init().
g_msbTemp
int32_t g_msbTemp[MODEL_MAX_OUT_CH_PER_ITER] static
Temporary buffer for storing MSB pass results.
Used during the NPU processing to store most significant byte results before combining with LSB results.
Referenced by FBFE_Init().
g_lsbTemp
int32_t g_lsbTemp[MODEL_MAX_OUT_CH_PER_ITER] static
Temporary buffer for storing LSB pass results.
Used during the NPU processing to store least significant byte results before combining with MSB results.
Referenced by FBFE_Init().
g_maxValues
int32_t g_maxValues[MODEL_CONV_OUT_CHANNELS] static
Buffer for storing maximum values across all strides.
This buffer holds the maximum activation values for each output channel across all stride iterations.
Referenced by FBFE_Init().
g_singleOut
uint8_t g_singleOut[MODEL_CONV_OUT_CHANNELS] static
Buffer for storing single iteration outputs.
This buffer holds the output from a single iteration of the NPU processing.
Referenced by FBFE_Init().
g_maxpool
uint8_t g_maxpool[MODEL_CONV_OUT_CHANNELS] static
Buffer for storing maxpool operation results.
This buffer holds the final maxpooled feature values after processing and scaling.
Referenced by FBFE_Init().
© Copyright 1995-2026, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale